/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/* GPIO_AD_25 (coord M15), LPUART1_RXD/J32[2] */
/* Routed pin properties */
#define BOARD_INITLPUARTPINS_LPUART1_RXD_PERIPHERAL                      LPUART1   /*!< Peripheral name */
#define BOARD_INITLPUARTPINS_LPUART1_RXD_SIGNAL                              RXD   /*!< Signal name */

/* GPIO_AD_24 (coord L13), LPUART1_TXD/J31[2] */
/* Routed pin properties */
#define BOARD_INITLPUARTPINS_LPUART1_TXD_PERIPHERAL                      LPUART1   /*!< Peripheral name */
#define BOARD_INITLPUARTPINS_LPUART1_TXD_SIGNAL                              TXD   /*!< Signal name */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitLpuartPins(void);              /* Function assigned for the Cortex-M7F */

/* GPIO_AD_30 (coord K17), DISP_BL */
/* Routed pin properties */
#define BOARD_INITMIPIPANELPINS_DISP_BL_PERIPHERAL                         GPIO9   /*!< Peripheral name */
#define BOARD_INITMIPIPANELPINS_DISP_BL_SIGNAL                           gpio_io   /*!< Signal name */
#define BOARD_INITMIPIPANELPINS_DISP_BL_CHANNEL                              29U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITMIPIPANELPINS_DISP_BL_GPIO                               GPIO9   /*!< GPIO peripheral base pointer */
#define BOARD_INITMIPIPANELPINS_DISP_BL_GPIO_PIN                             29U   /*!< GPIO pin number */
#define BOARD_INITMIPIPANELPINS_DISP_BL_GPIO_PIN_MASK                (1U << 29U)   /*!< GPIO pin mask */

/* GPIO_AD_02 (coord R13), DISP_RST */
/* Routed pin properties */
#define BOARD_INITMIPIPANELPINS_DISP_RST_PERIPHERAL                        GPIO9   /*!< Peripheral name */
#define BOARD_INITMIPIPANELPINS_DISP_RST_SIGNAL                          gpio_io   /*!< Signal name */
#define BOARD_INITMIPIPANELPINS_DISP_RST_CHANNEL                              1U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITMIPIPANELPINS_DISP_RST_GPIO                              GPIO9   /*!< GPIO peripheral base pointer */
#define BOARD_INITMIPIPANELPINS_DISP_RST_GPIO_PIN                             1U   /*!< GPIO pin number */
#define BOARD_INITMIPIPANELPINS_DISP_RST_GPIO_PIN_MASK                (1U << 1U)   /*!< GPIO pin mask */

/* GPIO_DISP_B2_15 (coord A4), DISP_POWER */
/* Routed pin properties */
#define BOARD_INITMIPIPANELPINS_DISP_POWER_PERIPHERAL                     GPIO11   /*!< Peripheral name */
#define BOARD_INITMIPIPANELPINS_DISP_POWER_SIGNAL                        gpio_io   /*!< Signal name */
#define BOARD_INITMIPIPANELPINS_DISP_POWER_CHANNEL                           16U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITMIPIPANELPINS_DISP_POWER_GPIO                           GPIO11   /*!< GPIO peripheral base pointer */
#define BOARD_INITMIPIPANELPINS_DISP_POWER_GPIO_PIN                          16U   /*!< GPIO pin number */
#define BOARD_INITMIPIPANELPINS_DISP_POWER_GPIO_PIN_MASK             (1U << 16U)   /*!< GPIO pin mask */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitMipiPanelPins(void);           /* Function assigned for the Cortex-M7F */

/* GPIO_DISP_B2_00 (coord E8), BT_CFG[6] */
/* Routed pin properties */
#define BOARD_INITMIPICAMERAPINS_CAMERA_PWDN_PERIPHERAL                   GPIO11   /*!< Peripheral name */
#define BOARD_INITMIPICAMERAPINS_CAMERA_PWDN_SIGNAL                      gpio_io   /*!< Signal name */
#define BOARD_INITMIPICAMERAPINS_CAMERA_PWDN_CHANNEL                          1U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITMIPICAMERAPINS_CAMERA_PWDN_GPIO                         GPIO11   /*!< GPIO peripheral base pointer */
#define BOARD_INITMIPICAMERAPINS_CAMERA_PWDN_GPIO_PIN                         1U   /*!< GPIO pin number */
#define BOARD_INITMIPICAMERAPINS_CAMERA_PWDN_GPIO_PIN_MASK            (1U << 1U)   /*!< GPIO pin mask */

/* GPIO_SNVS_00 (coord R10), J42[3] */
/* Routed pin properties */
#define BOARD_INITMIPICAMERAPINS_CAMERA_RST_PERIPHERAL                    GPIO13   /*!< Peripheral name */
#define BOARD_INITMIPICAMERAPINS_CAMERA_RST_SIGNAL                       gpio_io   /*!< Signal name */
#define BOARD_INITMIPICAMERAPINS_CAMERA_RST_CHANNEL                           3U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITMIPICAMERAPINS_CAMERA_RST_GPIO                          GPIO13   /*!< GPIO peripheral base pointer */
#define BOARD_INITMIPICAMERAPINS_CAMERA_RST_GPIO_PIN                          3U   /*!< GPIO pin number */
#define BOARD_INITMIPICAMERAPINS_CAMERA_RST_GPIO_PIN_MASK             (1U << 3U)   /*!< GPIO pin mask */

/* GPIO_AD_18 (coord M16), SAI1_RX_SYNC/J9[5]/J50[19]/U32[13] */
/* Routed pin properties */
#define BOARD_INITMIPICAMERAPINS_I2C2_SCL_PERIPHERAL                      LPI2C2   /*!< Peripheral name */
#define BOARD_INITMIPICAMERAPINS_I2C2_SCL_SIGNAL                             SCL   /*!< Signal name */

/* GPIO_AD_19 (coord L16), SAI1_RX_BCLK/J9[1]/J50[18]/U32[12] */
/* Routed pin properties */
#define BOARD_INITMIPICAMERAPINS_I2C2_SDA_PERIPHERAL                      LPI2C2   /*!< Peripheral name */
#define BOARD_INITMIPICAMERAPINS_I2C2_SDA_SIGNAL                             SDA   /*!< Signal name */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitMipiCameraPins(void);          /* Function assigned for the Cortex-M7F */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
