#!/bin/sh
./build_sdram_txt_debug.sh
./build_sdram_txt_release.sh
./build_flexspi_nor_sdram_debug.sh
./build_flexspi_nor_sdram_release.sh
./build_debug.sh
./build_release.sh
./build_sdram_debug.sh
./build_sdram_release.sh
./build_flexspi_nor_debug.sh
./build_flexspi_nor_release.sh
