/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/* GPIO_AD_25 (coord M15), LPUART1_RXD/J32[2] */
/* Routed pin properties */
#define BOARD_INITPINS_LPUART1_RXD_PERIPHERAL                            LPUART1   /*!< Peripheral name */
#define BOARD_INITPINS_LPUART1_RXD_SIGNAL                                    RXD   /*!< Signal name */

/* GPIO_AD_24 (coord L13), LPUART1_TXD/J31[2] */
/* Routed pin properties */
#define BOARD_INITPINS_LPUART1_TXD_PERIPHERAL                            LPUART1   /*!< Peripheral name */
#define BOARD_INITPINS_LPUART1_TXD_SIGNAL                                    TXD   /*!< Signal name */

/* GPIO_AD_21 (coord K14), SAI1_TXD[0]/J9[9]/J62[1]/BT_PCM_TXD/U16[9]/U354[6] */
/* Routed pin properties */
#define BOARD_INITPINS_BT_PCM_TXD_PERIPHERAL                                SAI1   /*!< Peripheral name */
#define BOARD_INITPINS_BT_PCM_TXD_SIGNAL                           sai_tx_data00   /*!< Signal name */

/* GPIO_AD_22 (coord K12), SAI1_TX_BCLK/J9[11]/BT_PCM_BCLK/U16[11]/U354[7]/U355[17] */
/* Routed pin properties */
#define BOARD_INITPINS_BT_PCM_BCLK_PERIPHERAL                               SAI1   /*!< Peripheral name */
#define BOARD_INITPINS_BT_PCM_BCLK_SIGNAL                            sai_tx_bclk   /*!< Signal name */

/* GPIO_AD_23 (coord J12), SAI1_TX_SYNC/J9[13]/BT_PCM_SYNC/U16[8]/U354[8]/U355[16] */
/* Routed pin properties */
#define BOARD_INITPINS_BT_PCM_SYNC_PERIPHERAL                               SAI1   /*!< Peripheral name */
#define BOARD_INITPINS_BT_PCM_SYNC_SIGNAL                            sai_tx_sync   /*!< Signal name */

/* GPIO_LPSR_08 (coord U8), DMIC_CLK/U41[1]/U44[1]/J50[18] */
/* Routed pin properties */
#define BOARD_INITPINS_I2C5_SDA_PERIPHERAL                                LPI2C5   /*!< Peripheral name */
#define BOARD_INITPINS_I2C5_SDA_SIGNAL                                       SDA   /*!< Signal name */

/* GPIO_LPSR_09 (coord P5), DMIC_DATA0/U41[5]/J50[20]/LPSPI6_CS0/J26[11] */
/* Routed pin properties */
#define BOARD_INITPINS_I2C5_SCL_PERIPHERAL                                LPI2C5   /*!< Peripheral name */
#define BOARD_INITPINS_I2C5_SCL_SIGNAL                                       SCL   /*!< Signal name */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);                    /* Function assigned for the Cortex-M7F */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
