/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/* GPIO_AD_25 (coord M15), LPUART1_RXD/J32[2] */
/* Routed pin properties */
#define BOARD_INITPINS_LPUART1_RXD_PERIPHERAL                            LPUART1   /*!< Peripheral name */
#define BOARD_INITPINS_LPUART1_RXD_SIGNAL                                    RXD   /*!< Signal name */

/* GPIO_AD_24 (coord L13), LPUART1_TXD/J31[2] */
/* Routed pin properties */
#define BOARD_INITPINS_LPUART1_TXD_PERIPHERAL                            LPUART1   /*!< Peripheral name */
#define BOARD_INITPINS_LPUART1_TXD_SIGNAL                                    TXD   /*!< Signal name */

/* GPIO_AD_04 (coord M13), SIM1_PD/J44[C8]/USER_LED_CTL1/J9[8]/J25[7] */
/* Routed pin properties */
#define BOARD_INITPINS_SIM1_PD_PERIPHERAL                                  GPIO9   /*!< Peripheral name */
#define BOARD_INITPINS_SIM1_PD_SIGNAL                                    gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SIM1_PD_CHANNEL                                        3U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SIM1_PD_GPIO                                        GPIO9   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SIM1_PD_GPIO_PIN                                       3U   /*!< GPIO pin number */
#define BOARD_INITPINS_SIM1_PD_GPIO_PIN_MASK                          (1U << 3U)   /*!< GPIO pin mask */

/* GPIO_AD_14 (coord N14), SPDIF_EXT_CLK/CAN_STBY/J9[16] */
/* Routed pin properties */
#define BOARD_INITPINS_LED1_PERIPHERAL                                     GPIO9   /*!< Peripheral name */
#define BOARD_INITPINS_LED1_SIGNAL                                       gpio_io   /*!< Signal name */
#define BOARD_INITPINS_LED1_CHANNEL                                          13U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED1_GPIO                                           GPIO9   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_LED1_GPIO_PIN                                         13U   /*!< GPIO pin number */
#define BOARD_INITPINS_LED1_GPIO_PIN_MASK                            (1U << 13U)   /*!< GPIO pin mask */

/* GPIO_LPSR_13 (coord U6), GND */
/* Routed pin properties */
#define BOARD_INITPINS_LED2_PERIPHERAL                                    GPIO12   /*!< Peripheral name */
#define BOARD_INITPINS_LED2_SIGNAL                                       gpio_io   /*!< Signal name */
#define BOARD_INITPINS_LED2_CHANNEL                                          13U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED2_GPIO                                          GPIO12   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_LED2_GPIO_PIN                                         13U   /*!< GPIO pin number */
#define BOARD_INITPINS_LED2_GPIO_PIN_MASK                            (1U << 13U)   /*!< GPIO pin mask */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);                    /* Function assigned for the Cortex-M7F */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
