name: Publish Repo Selectively
on: [push, workflow_dispatch]
jobs:
  call_selective_push:
    uses: phytec/gh-action-tools/.github/workflows/selective-push.yml@main
    with:
      BRANCHES: "main v2.13.0-phy"
    secrets: inherit
